services:
  be:
    build: ./be
    container_name: qstat_backend
    volumes:
      - ./be/src:/app/src
      - ./.env:/app/.env
      - ./data:/app/data
    ports:
      - "8000:8000"
    env_file:
      - .env
  fe:
    build: ./fe
    container_name: qstat_frontend
    volumes:
      - ./fe/src:/app/src
      - ./fe/index.html:/app/index.html
    ports:
      - "5173:5173"
    depends_on:
      - be
  chromadb:
    image: chromadb/chroma:latest
    container_name: qstat_chromadb
    ports:
      - "8100:8000"
    volumes:
      - ./chroma_data:/chroma/chroma
  mcp:
    build: ./mcp
    container_name: qstat_mcp
    volumes:
      - ./mcp/src:/app/src
      - ./.env:/app/.env
    ports:
      - "8200:8200"
    env_file:
      - .env
    depends_on:
      - be